babystore/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from items import urls as items
from reactfilebrowser import urls as filebrowser
from django.conf.urls.static import static
from filebrowser.sites import site

urlpatterns = [
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^reactfilebrowser/', include(filebrowser, namespace="reactfilebrowser")),
    url(r'^items/', include(filebrowser, namespace="reactfilebrowser")),
    url(r'^comments/', include('django_comments.urls')),
    # url(r'^custom_comments/', include('custom_comments.urls', namespace="custom_comments")),
]

urlpatterns += i18n_patterns(
    url(_(r'^admin/'), admin.site.urls),
    url(_(r'^items/'), include(items, namespace="items")),
    url(_(r'^ckeditor/'), include('ckeditor_uploader.urls')),
    url(_(r'^custom_comments/'), include('custom_comments.urls', namespace="custom_comments")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # url(
        #     r'^media/(?P<path>.*)$', serve,
        #     {
        #         'document_root': settings.MEDIA_ROOT
        #     }
        # ),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

custom_comments/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from custom_comments.views import CommentList

urlpatterns = [
    url(r'list/(?P<object_slug>[a-z0-9-]+)/(?P<page>[0-9]+)/$', CommentList.as_view(), name="custom_comments_list"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

items/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from items.views.views import ProductList, ProductDetails
from items.views.rest_view import ProductListApi, ProductDetailApi

urlpatterns = [
    url(r'list/page/(?P<page>[0-9]+)/$', ProductList.as_view(), name="product_list"),
    url(r'listapi/page/(?P<page>[0-9]+)/$', ProductListApi.as_view(), name="product_list_api"),
    url(r'details/(?P<slug>[a-z0-9-]+)/$', ProductDetails.as_view(), name="product_details"),
    url(r'detailsapi/(?P<slug>[a-z0-9-]+)/$', ProductDetailApi.as_view(), name="product_details_api"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

items/models.py
import uuid
from enum import Enum

from django.contrib.postgres.fields.array import ArrayField
from django.utils.datetime_safe import datetime
from django.utils.timezone import utc
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import get_language

from items.managers import ItemManager


class ItemTypeEnum(Enum):
    MAIN_ITEM = 0
    SUB_ITEM = 1

    @staticmethod
    def get_choices():
        return (
            (ItemTypeEnum.MAIN_ITEM.value, _("Main item")),
            (ItemTypeEnum.SUB_ITEM.value, _("Sub item"))
        )


class Item(models.Model):
    item_manager = ItemManager()
    objects = models.Manager()
    name = models.CharField(max_length=150, verbose_name=_('Name'),
                            help_text=_('Maximum %(count)d symbols are allowed') % {"count": 150})
    slug = models.SlugField(max_length=50, unique=True,
                            help_text=_('Unique value for product page URL, created from name.'))
    unique_code = models.UUIDField(default=uuid.uuid4)
    sku = models.CharField(max_length=50, help_text=_("Stock-keeping unit"), unique=True)
    #
    is_active = models.BooleanField(default=True, verbose_name=_("Is active"))
    is_bestseller = models.BooleanField(default=False)
    key_features_en = ArrayField(models.CharField(max_length=150), verbose_name=_("Key Features"), blank=True,
                                 null=True,
                                 size=10)
    specification_en = ArrayField(models.CharField(max_length=150), verbose_name=_("Specification"), blank=True,
                                  null=True,
                                  size=10)
    key_features_ka = ArrayField(models.CharField(max_length=150), verbose_name=_("Key Features") + "[ka]", blank=True,
                                 null=True,
                                 size=10)

    specification_ka = ArrayField(models.CharField(max_length=150), verbose_name=_("Specification") + "[ka]",
                                  blank=True,
                                  null=True,
                                  size=10)
    type = models.IntegerField(choices=ItemTypeEnum.get_choices(), default=ItemTypeEnum.MAIN_ITEM.value,
                               verbose_name=_("Type"))
    description = models.TextField(verbose_name=_('Description'))

    brand = models.ForeignKey('ItemBrand', verbose_name=_('Brand'), null=True, blank=True)
    age = models.ForeignKey('ItemAge', verbose_name=_("Age range"))
    color = models.ForeignKey('ItemColor', verbose_name=_("Color"))
    categories = models.ManyToManyField("ItemCategory", verbose_name=_("Categories"), blank=True)
    images = ArrayField(models.CharField(max_length=9999), verbose_name=_("Images"), blank=True, null=True, size=20)
    meta_keywords = models.CharField(max_length=255,
                                     help_text=_('Comma-delimited set of SEO keywords for meta tag'))
    meta_description = models.CharField(max_length=255,
                                        help_text=_('Content for description meta tag'))
    price = models.DecimalField(default=0, decimal_places=2, max_digits=9, verbose_name=_("Price"))
    old_price = models.DecimalField(default=0, decimal_places=2, max_digits=9, verbose_name=_("Old price"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created date"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Update time"))

    parent = models.ForeignKey("self", null=True, blank=True, verbose_name=_("Parent"))
    variant_of = models.ForeignKey("self", null=True, blank=True, verbose_name=_("Variant of"),
                                   related_name="variant_fo")

    def __str__(self):
        return self.name_ka if get_language() == "ka"else self.name_en

    @property
    def is_variant(self):
        return self.variant_of is not None

    @property
    def in_stock(self):
        if hasattr(self, "_in_stock"):
            return self._in_stock
        return self.stockitemmembership_set.filter(quantity__gt=0).count() > 0

    @property
    def is_new(self):
        now = datetime.utcnow().replace(tzinfo=utc)
        time_diff = now - self.created_at
        return time_diff.total_seconds() < 60 * 60 * 24 * 3

    # in_stock.short_description = _("In stock")
    @models.permalink
    def get_absolute_url(self):
        # from django.core.urlresolvers import reverse
        return "items:product_details", (), {"slug": self.slug}

    class Meta:
        verbose_name = _('Item')
        verbose_name_plural = _('Items')
        ordering = ["-created_at", "-updated_at"]


class ItemColor(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"),
                            help_text=_('Maximum %(count)d symbols are allowed') % {"count": 200})
    value = models.CharField(max_length=10, verbose_name=_("Name"),
                             help_text=_('Maximum %(count)d symbols are allowed') % {"count": 10})

    @property
    def display_color(self):
        return mark_safe(
            "<div><div style='display:inline-block;background-color:{0}; width:3rem;height:1rem;'></div> <span>{1}</span></div>".format(
                self.value,
                self.value
            ))

    def __str__(self):
        return self.name_ka if get_language() == "ka" else self.name_en

    class Meta:
        verbose_name = _('Color')
        verbose_name_plural = _('Colors')


class ItemBrand(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"),
                            help_text=_('Maximum %(count)d symbols are allowed') % {"count": 200})
    description = models.TextField(verbose_name=_("Description"))

    country = models.CharField(max_length=200, verbose_name=_("Country"),
                               help_text=_('Maximum %(count)d symbols are allowed') % {"count": 200})

    def __str__(self):
        return self.name_ka if get_language() == "ka" else self.name_en

    class Meta:
        verbose_name = _('Brand')
        verbose_name_plural = _('Brands')


class AgeUnitEnum(Enum):
    YEAR = 0
    MONTH = 1

    @staticmethod
    def get_choices():
        return (
            (AgeUnitEnum.YEAR.value, _("Year")),
            (AgeUnitEnum.MONTH.value, _("Month"))
        )


class ItemAge(models.Model):
    age_from = models.IntegerField(verbose_name=_("From age"))
    age_to = models.IntegerField(verbose_name=_("To age"))
    unit = models.IntegerField(choices=AgeUnitEnum.get_choices(), verbose_name=_("unit"))
    description = models.TextField(verbose_name=_("Description"))

    def __str__(self):
        return "{0}-{1} {2}".format(self.age_from, self.age_to, self.get_unit_display())

    class Meta:
        verbose_name = _('Age range')
        verbose_name_plural = _('Age ranges')


class ItemCategory(models.Model):
    unique_code = models.UUIDField(
        verbose_name=_('Unique code'),
        default=uuid.uuid4,
        editable=False
    )
    name = models.CharField(max_length=150, verbose_name=_('Name'),
                            help_text=_('Maximum %(count)d symbols are allowed') % {"count": 150})
    description = models.TextField(verbose_name=_('Description'))

    # parent = models.ForeignKey("self", verbose_name=_("Parent"), null=True, blank=True)

    def __str__(self):
        return self.name_ka if get_language() == "ka"else self.name_en

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

items/views/rest_view.py
from rest_framework import generics
from rest_framework.pagination import PageNumberPagination
from items.serializers import ItemSerializer, ItemDetailViewSerializer
from items.models import Item


class LargeResultsSetPagination(PageNumberPagination):
    page_size = 2


class ProductListApi(generics.ListAPIView):
    queryset = Item.item_manager.get_item_list()
    pagination_class = LargeResultsSetPagination
    serializer_class = ItemSerializer


class ProductDetailApi(generics.RetrieveUpdateDestroyAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemDetailViewSerializer
    lookup_field = 'slug'

    def get(self, *args, **kwargs):
        response = super().get(*args, **kwargs)
        response["Access-Control-Allow-Origin"] = "*"
        return response

items/views/views.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from items.models import Item


class ProductList(ListView):
    model = Item
    template_name = "items/product_list/index.html"
    paginate_by = 2

    def get_queryset(self):
        return Item.item_manager.get_item_list()


class ProductDetails(DetailView):
    model = Item
    template_name = "items/single_product/index.html"

    def get_queryset(self):
        return Item.item_manager.select_related("brand")

items/templates/items/single_product/index.html
{% extends "items/base_full_width.html" %}
{% load staticfiles %}
{% block style %}
    <link href="{% static 'themforest/plugins/bootstrap-select/css/bootstrap-select.min.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'items/single_page_image_paging.css' %}" rel="stylesheet"/>
    <link href="{% static 'items/owl.carousel/owl.carousel.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'themforest/plugins/owl-carousel/owl.carousel.css' %}" rel="stylesheet"/>
    <link href="{% static 'items/owl.carousel/owl.theme.default.min.css' %}" rel="stylesheet"/>
    <script src="{% static "items/products.js" %}"></script>
{% endblock style %}

{% load base_filters %}
{% block product_content %}
    {#    <aside class="col-md-9 col-sm-8">#}
    <!-- Single Products Start -->
    {% include "items/single_product/product.html" %}
    <!-- Single Products Ends -->

    <!-- Single Products Description Start -->
    {% include "items/single_product/product_description.html" %}
    <!-- Single Products Description Ends -->

    <!-- Related Products Start -->
    {% include "items/single_product/related_products.html" %}
    <!-- / Related Products Ends -->
    {#    </aside>#}
{% endblock product_content %}
{% block script %}
    <script src="{% static "themforest/plugins/bootstrap-select/js/bootstrap-select.min.js" %}"></script>
    <script src="{% static "themforest/plugins/owl-carousel/owl.carousel.min.js" %}"></script>
    <script src="{% static "themforest/js/theme.js" %}"></script>
{% endblock script %}

items/templates/items/single_product/product.html
{% load i18n %}
{% load staticfiles %}
{% load base_filters %}
{% load items_helper_tags %}
<section id="product-fullwidth" class="space-bottom-45">
    <div class="single-product-wrap">
        <div class="list-category-details">
            <div class="row">
                <div class="col-md-7 col-sm-12">
                    <div class="row" id="slider">
                    </div>
                </div>
                <div class="col-md-5 col-sm-12">
                    <div class="product-content">
                        {% rating_tag object %}
                        <div class="product-name">
                            <h4>{{ object.name }}</h4>
                        </div>
                        <div id="metaData">
                        </div>
                        <div class="add-to-cart">
                            <a class="blue-btn btn" href="#"> <i
                                    class="fa fa-shopping-cart white-color"></i> Add to Cart</a>
                            <a class="btn default-btn" href="#"> <i class="fa fa-heart"></i> </a>
                            <a class="btn default-btn" href="#"> <i class="fa fa-eye"></i> </a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {
        babyStore.InitializeSingleProduct({
            api_url: "{% url "items:product_details_api" object.slug %}",
            media_root: "{{ MEDIA_URL }}"
        });
    });
</script>

items/templates/items/single_product/product_description.html
{% load i18n %}
{% load staticfiles %}
{% load base_filters %}
<section id="description-item">
    <div class="row">
        <div class="col-md-8 col-sm-8">
            <!-- Product Best Sellers Start -->
            <section id="single-product-tabination" class="space-bottom-45">
                <div class="light-bg product-tabination default-box-shadow">
                    <div class="tabination">
                        <div class="product-tabs" role="tabpanel">
                            <!-- Nav tabs -->
                            <ul role="tablist" class="nav nav-tabs navtab-horizontal">
                                <li role="presentation" class="active">
                                    <a class="green-background" data-toggle="tab" role="tab"
                                       href="#description" aria-expanded="true">{% trans "Description" %}</a>
                                </li>
                                <li role="presentation">
                                    <a class="pink-background" data-toggle="tab" role="tab"
                                       href="#brand-info" aria-expanded="false">{% trans "Brand Info" %}</a>
                                </li>
                                <li role="presentation" class="">
                                    <a data-toggle="tab" class="golden-background" role="tab"
                                       href="#reviews" aria-expanded="false">{% trans "Reviews" %}</a>
                                </li>
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <!-- =============================== Description ============================= -->
                                <div id="description" class="tab-pane fade active in"
                                     role="tabpanel">
                                    <div class="col-md-12 product-wrap">
                                        <div class="title-wrap">
                                            <h2 class="section-title">
                                                <span>
                                                    <span class="funky-font blue-tag">{% trans "Product" %} </span>
                                                    <span class="italic-font">{% trans "Description" %} </span>
                                                </span>
                                            </h2>
                                        </div>
                                        <div class="product-disc space-bottom-35">
                                            <p>
                                                {{ object|translate:"description"|safe }}
                                            </p>
                                            <div class="row circle-list-box">
                                                <div class="box-left col-md-6 col-sm-6">
                                                    <h2 class="title-2 sub-title-small">
                                                        {% trans 'Key Features' %}
                                                    </h2>
                                                    <ul class="circle-list">
                                                        {% for feature in object|translate:"key_features" %}
                                                            <li> {{ feature }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                </div>
                                                <div class="box-right col-md-6 col-sm-6">
                                                    <h2 class="title-2 sub-title-small">
                                                        {% trans 'Specification' %}
                                                    </h2>
                                                    <ul class="circle-list">
                                                        {% for specification in object|translate:"specification" %}
                                                            <li> {{ specification }}</li>
                                                        {% endfor %}
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- ====================== Brand Info ======================== -->
                                <div id="brand-info" class="tab-pane fade" role="tabpanel">
                                    <div class="col-md-12 product-wrap">
                                        <div class="title-wrap">
                                            <h2 class="section-title">
                                                <span>
                                                    <span class="funky-font blue-tag">{% trans "Product" %}</span>
                                                    <span class="italic-font">{% trans "Brand" %}</span>
                                                </span>
                                            </h2>
                                        </div>
                                        <div class="product-disc space-bottom-35">
                                            <p>
                                                {{ object.brand|translate:"description"|safe }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <!-- ====================== Reviews ======================== -->
                                <div id="reviews" class="tab-pane fade" role="tabpanel">
                                    <div class="col-md-12 product-wrap">
                                        <div class="title-wrap  text-center space-bottom-25">
                                            <h2 class="section-title with-border">
                                                <span class="white-bg">
                                                    <span class="funky-font pink-tag">{% trans 'Reviews' %}</span>
                                                    <span class="italic-font">{% trans 'Ratings' %} </span>
                                                </span>
                                            </h2>
                                        </div>
                                        <div class="product-disc space-bottom-35">
                                            <div class="col-md-12 col-sm-12 space-bottom-45">
                                                {% include "items/single_product/reviews.html" %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- / Product Best Sellers Ends -->
        </div>
        <div class="col-md-4 col-sm-4">
            {% load items_helper_tags %}
            {% top_rated %}
        </div>
    </div>
</section>

items/templates/items/single_product/reviews.html
{% load i18n %}
{% load comments %}
<div class="account-details-wrap">
    {#    <div class="title-2 sub-title-small">Your Reviews and Ratings</div>#}
    <table class="product-table">
        <tbody>
        {% render_top_comment_list for object %}
        </tbody>
    </table>
</div>
{% get_comment_count for object as comment_count %}
<p>
    <a class="text-info" href="{% url "custom_comments:custom_comments_list" object.slug 0 %}">
        {% blocktrans with count=comment_count %}
            read all {{ count }} comments
        {% endblocktrans %}

    </a>
</p>