babystore/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from items import urls as items
from reactfilebrowser import urls as filebrowser
from django.conf.urls.static import static
from filebrowser.sites import site

urlpatterns = [
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^reactfilebrowser/', include(filebrowser, namespace="reactfilebrowser")),
    url(r'^items/', include(filebrowser, namespace="reactfilebrowser")),
    url(r'^comments/', include('django_comments.urls')),
    # url(r'^custom_comments/', include('custom_comments.urls', namespace="custom_comments")),
]

urlpatterns += i18n_patterns(
    url(_(r'^admin/'), admin.site.urls),
    url(_(r'^items/'), include(items, namespace="items")),
    url(_(r'^ckeditor/'), include('ckeditor_uploader.urls')),
    url(_(r'^custom_comments/'), include('custom_comments.urls', namespace="custom_comments")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # url(
        #     r'^media/(?P<path>.*)$', serve,
        #     {
        #         'document_root': settings.MEDIA_ROOT
        #     }
        # ),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

items/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from items.views.views import ProductList, ProductDetails
from items.views.rest_view import ProductListApi, ProductDetailApi

urlpatterns = [
    url(r'list/page/(?P<page>[0-9]+)/$', ProductList.as_view(), name="product_list"),
    url(r'listapi/page/(?P<page>[0-9]+)/$', ProductListApi.as_view(), name="product_list_api"),
    url(r'details/(?P<slug>[a-z0-9-]+)/$', ProductDetails.as_view(), name="product_details"),
    url(r'detailsapi/(?P<slug>[a-z0-9-]+)/$', ProductDetailApi.as_view(), name="product_details_api"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

items/models.py
import uuid
from enum import Enum

from django.contrib.postgres.fields.array import ArrayField
from django.utils.datetime_safe import datetime
from django.utils.timezone import utc
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import get_language

from items.managers import ItemManager


class ItemTypeEnum(Enum):
    MAIN_ITEM = 0
    SUB_ITEM = 1

    @staticmethod
    def get_choices():
        return (
            (ItemTypeEnum.MAIN_ITEM.value, _("Main item")),
            (ItemTypeEnum.SUB_ITEM.value, _("Sub item"))
        )


class Item(models.Model):
    item_manager = ItemManager()
    objects = models.Manager()
    name = models.CharField(max_length=150, verbose_name=_('Name'),
                            help_text=_('Maximum %(count)d symbols are allowed') % {"count": 150})
    slug = models.SlugField(max_length=50, unique=True,
                            help_text=_('Unique value for product page URL, created from name.'))
    unique_code = models.UUIDField(default=uuid.uuid4)
    sku = models.CharField(max_length=50, help_text=_("Stock-keeping unit"), unique=True)
    #
    is_active = models.BooleanField(default=True, verbose_name=_("Is active"))
    is_bestseller = models.BooleanField(default=False)
    key_features_en = ArrayField(models.CharField(max_length=150), verbose_name=_("Key Features"), blank=True,
                                 null=True,
                                 size=10)
    specification_en = ArrayField(models.CharField(max_length=150), verbose_name=_("Specification"), blank=True,
                                  null=True,
                                  size=10)
    key_features_ka = ArrayField(models.CharField(max_length=150), verbose_name=_("Key Features") + "[ka]", blank=True,
                                 null=True,
                                 size=10)

    specification_ka = ArrayField(models.CharField(max_length=150), verbose_name=_("Specification") + "[ka]",
                                  blank=True,
                                  null=True,
                                  size=10)
    type = models.IntegerField(choices=ItemTypeEnum.get_choices(), default=ItemTypeEnum.MAIN_ITEM.value,
                               verbose_name=_("Type"))
    description = models.TextField(verbose_name=_('Description'))

    brand = models.ForeignKey('ItemBrand', verbose_name=_('Brand'), null=True, blank=True)
    age = models.ForeignKey('ItemAge', verbose_name=_("Age range"))
    color = models.ForeignKey('ItemColor', verbose_name=_("Color"))
    categories = models.ManyToManyField("ItemCategory", verbose_name=_("Categories"), blank=True)
    images = ArrayField(models.CharField(max_length=9999), verbose_name=_("Images"), blank=True, null=True, size=20)
    meta_keywords = models.CharField(max_length=255,
                                     help_text=_('Comma-delimited set of SEO keywords for meta tag'))
    meta_description = models.CharField(max_length=255,
                                        help_text=_('Content for description meta tag'))
    price = models.DecimalField(default=0, decimal_places=2, max_digits=9, verbose_name=_("Price"))
    old_price = models.DecimalField(default=0, decimal_places=2, max_digits=9, verbose_name=_("Old price"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created date"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Update time"))

    parent = models.ForeignKey("self", null=True, blank=True, verbose_name=_("Parent"))
    variant_of = models.ForeignKey("self", null=True, blank=True, verbose_name=_("Variant of"),
                                   related_name="variant_fo")

    def __str__(self):
        return self.name_ka if get_language() == "ka"else self.name_en

    @property
    def is_variant(self):
        return self.variant_of is not None

    @property
    def in_stock(self):
        if hasattr(self, "_in_stock"):
            return self._in_stock
        return self.stockitemmembership_set.filter(quantity__gt=0).count() > 0

    @property
    def is_new(self):
        now = datetime.utcnow().replace(tzinfo=utc)
        time_diff = now - self.created_at
        return time_diff.total_seconds() < 60 * 60 * 24 * 3

    # in_stock.short_description = _("In stock")
    @models.permalink
    def get_absolute_url(self):
        # from django.core.urlresolvers import reverse
        return "items:product_details", (), {"slug": self.slug}

    class Meta:
        verbose_name = _('Item')
        verbose_name_plural = _('Items')
        ordering = ["-created_at", "-updated_at"]


class ItemColor(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"),
                            help_text=_('Maximum %(count)d symbols are allowed') % {"count": 200})
    value = models.CharField(max_length=10, verbose_name=_("Name"),
                             help_text=_('Maximum %(count)d symbols are allowed') % {"count": 10})

    @property
    def display_color(self):
        return mark_safe(
            "<div><div style='display:inline-block;background-color:{0}; width:3rem;height:1rem;'></div> <span>{1}</span></div>".format(
                self.value,
                self.value
            ))

    def __str__(self):
        return self.name_ka if get_language() == "ka" else self.name_en

    class Meta:
        verbose_name = _('Color')
        verbose_name_plural = _('Colors')


class ItemBrand(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"),
                            help_text=_('Maximum %(count)d symbols are allowed') % {"count": 200})
    description = models.TextField(verbose_name=_("Description"))

    country = models.CharField(max_length=200, verbose_name=_("Country"),
                               help_text=_('Maximum %(count)d symbols are allowed') % {"count": 200})

    def __str__(self):
        return self.name_ka if get_language() == "ka" else self.name_en

    class Meta:
        verbose_name = _('Brand')
        verbose_name_plural = _('Brands')


class AgeUnitEnum(Enum):
    YEAR = 0
    MONTH = 1

    @staticmethod
    def get_choices():
        return (
            (AgeUnitEnum.YEAR.value, _("Year")),
            (AgeUnitEnum.MONTH.value, _("Month"))
        )


class ItemAge(models.Model):
    age_from = models.IntegerField(verbose_name=_("From age"))
    age_to = models.IntegerField(verbose_name=_("To age"))
    unit = models.IntegerField(choices=AgeUnitEnum.get_choices(), verbose_name=_("unit"))
    description = models.TextField(verbose_name=_("Description"))

    def __str__(self):
        return "{0}-{1} {2}".format(self.age_from, self.age_to, self.get_unit_display())

    class Meta:
        verbose_name = _('Age range')
        verbose_name_plural = _('Age ranges')


class ItemCategory(models.Model):
    unique_code = models.UUIDField(
        verbose_name=_('Unique code'),
        default=uuid.uuid4,
        editable=False
    )
    name = models.CharField(max_length=150, verbose_name=_('Name'),
                            help_text=_('Maximum %(count)d symbols are allowed') % {"count": 150})
    description = models.TextField(verbose_name=_('Description'))

    # parent = models.ForeignKey("self", verbose_name=_("Parent"), null=True, blank=True)

    def __str__(self):
        return self.name_ka if get_language() == "ka"else self.name_en

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

items/views/rest_view.py
from rest_framework import generics
from rest_framework.pagination import PageNumberPagination
from items.serializers import ItemSerializer, ItemDetailViewSerializer
from items.models import Item


class LargeResultsSetPagination(PageNumberPagination):
    page_size = 2


class ProductListApi(generics.ListAPIView):
    queryset = Item.item_manager.get_item_list()
    pagination_class = LargeResultsSetPagination
    serializer_class = ItemSerializer


class ProductDetailApi(generics.RetrieveUpdateDestroyAPIView):
    queryset = Item.objects.all()
    serializer_class = ItemDetailViewSerializer
    lookup_field = 'slug'

    def get(self, *args, **kwargs):
        response = super().get(*args, **kwargs)
        response["Access-Control-Allow-Origin"] = "*"
        return response

items/views/views.py
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from items.models import Item


class ProductList(ListView):
    model = Item
    template_name = "items/product_list/index.html"
    paginate_by = 2

    def get_queryset(self):
        return Item.item_manager.get_item_list()


class ProductDetails(DetailView):
    model = Item
    template_name = "items/single_product/index.html"

    def get_queryset(self):
        return Item.item_manager.select_related("brand")

items/templates/items/product_list/header_footer/paging.html
<div class="inline-block">
    <div class="pagination-wrapper">
        <ul class="pagination-list">
            {% if page_obj.number > 3 %}
                <li><a href="{% url "items:product_list" 1 %}"> 1 </a></li>
                <li>...</li>
                <li>
                    <a href="{% url "items:product_list" page_obj.previous_page_number %}">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
                <li class="active">
                    <a href="{% url "items:product_list" page_obj.number %}">
                        {{ page_obj.number }}
                    </a>
                </li>
                {% if  page_obj.has_next %}
                    <li>
                        <a href="{% url "items:product_list" page_obj.next_page_number %}">
                            {{ page_obj.next_page_number }}
                        </a>
                    </li>
                {% endif %}
            {% else %}
                <li {% if page_obj.number == 1 %}class="active"{% endif %}>
                    <a href="{% url "items:product_list" 1 %}">
                        1
                    </a>
                </li>
                <li {% if page_obj.number == 2 %}class="active"{% endif %}>
                    <a href="{% url "items:product_list" 2 %}">
                        2
                    </a>
                </li>
                {% if page_obj.number == 3 %}
                    <li class="active">
                        <a href="{% url "items:product_list" 3 %}">
                            3
                        </a>
                    </li>
                    {% if  page_obj.has_next %}
                        <li>
                            <a href="{% url "items:product_list" page_obj.next_page_number %}">
                                {{ page_obj.next_page_number }}
                            </a>
                        </li>
                    {% endif %}
                {% else %}
                    <li>
                        <a href="{% url "items:product_list" 3 %}">
                            3
                        </a>
                    </li>
                {% endif %}

            {% endif %}
            {% if  page_obj.has_next and page_obj.next_page_number < paginator.num_pages %}
                <li>
                    ...
                </li>
                <li>
                    <a href="{% url "items:product_list" paginator.num_pages %}">
                        {{ paginator.num_pages }}
                    </a>
                </li>
                <li class="nxt">
                <a href="{% url "items:product_list" page_obj.next_page_number %}"> <i class=" fa fa-angle-right"></i>
                </a>
            {% endif %}

            </li>
        </ul>
    </div>
</div>

items/templates/items/product_list/header_footer/products_footer.html
{% load base_tags %}
<div class="light-bg sorter">
    {% if is_paginated %}
        <div class="col-md-6 col-sm-12 show-items">
            <span>Showing Items : {{ page_obj.start_index }} to {{ page_obj.end_index }} total {{ paginator.count }}</span>
        </div>

        <div class="col-md-6 col-sm-12 bottom-pagination text-right">
            {% paging_tag paginator page_obj %}
            {#                        {% include "items/header_footer/pagin.html" %}#}
        </div>
    {% endif %}
</div>

items/templates/items/product_list/header_footer/products_header.html
{% load base_tags %}
<div class="light-bg margin-30 sorter">
    <div class="col-md-6 col-sm-12">
        <div class="row">
            <div class="view-as col-md-5 col-sm-4">
                <span>View as:</span>
                <div class="inline-block">
                    <ul class="nav-tabs tabination">
                        <li class="active">
                            <a data-toggle="tab" href="#grid-view" aria-expanded="true">
                                <i class="fa fa-th-large"></i>
                            </a>
                        </li>
                        <li>
                            <a data-toggle="tab" href="#list-view" aria-expanded="false">
                                <i class="fa fa-th-list"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="sort-by col-md-7 col-sm-8 no-padding">
                <span>Sort By:</span>
                <div class="inline-block">
                    <form class="filter-form">
                        <div class="form-group selectpicker-wrapper">
                            <select
                                    class="selectpicker input-price" data-live-search="true"
                                    data-width="100%"
                                    data-toggle="tooltip" title="Best Sellers">
                                <option>Most Popular</option>
                                <option>Latest Items</option>
                                <option>Best Sellers</option>
                            </select>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <div class="row">
            {% if is_paginated %}
                <div class="show-as col-md-4 col-sm-4 no-padding text-right">
                    <span>Show:</span>
                    <div class="inline-block">
                        <form class="filter-form">
                            <div class="form-group selectpicker-wrapper">
                                <select
                                        class="selectpicker input-price" data-live-search="true"
                                        data-width="100%"
                                        data-toggle="tooltip" title="16">
                                    <option>20</option>
                                    <option>24</option>
                                    <option>All</option>
                                </select>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="page-by col-md-8 col-sm-8 text-right">
                    <span>Page:</span>
                    {% paging_tag paginator page_obj %}
                </div>
            {% endif %}
        </div>
    </div>
</div>