babystore/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from items import urls as items
from reactfilebrowser import urls as filebrowser
from django.conf.urls.static import static
from filebrowser.sites import site

urlpatterns = [
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^reactfilebrowser/', include(filebrowser, namespace="reactfilebrowser")),
    url(r'^items/', include(filebrowser, namespace="reactfilebrowser")),
    url(r'^comments/', include('django_comments.urls')),
    # url(r'^custom_comments/', include('custom_comments.urls', namespace="custom_comments")),
]

urlpatterns += i18n_patterns(
    url(_(r'^admin/'), admin.site.urls),
    url(_(r'^items/'), include(items, namespace="items")),
    url(_(r'^ckeditor/'), include('ckeditor_uploader.urls')),
    url(_(r'^custom_comments/'), include('custom_comments.urls', namespace="custom_comments")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # url(
        #     r'^media/(?P<path>.*)$', serve,
        #     {
        #         'document_root': settings.MEDIA_ROOT
        #     }
        # ),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

items/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from items.views.views import ProductList, ProductDetails
from items.views.rest_view import ProductListApi, ProductDetailApi

urlpatterns = [
    url(r'list/page/(?P<page>[0-9]+)/$', ProductList.as_view(), name="product_list"),
    url(r'listapi/page/(?P<page>[0-9]+)/$', ProductListApi.as_view(), name="product_list_api"),
    url(r'details/(?P<slug>[a-z0-9-]+)/$', ProductDetails.as_view(), name="product_details"),
    url(r'detailsapi/(?P<slug>[a-z0-9-]+)/$', ProductDetailApi.as_view(), name="product_details_api"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

reactfilebrowser/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from reactfilebrowser.views import get_root, get_browser, test

urlpatterns = [
    url(r'root/$', get_root, name="root"),
    url(r'browser/(?P<opener_id>[-\w]+)/$', get_browser, name="browser"),
    url(r'browser/$', get_browser, name="browser"),
    url(r'test/$', test, name="test"),
]
urlpatterns = format_suffix_patterns(urlpatterns)

reactfilebrowser/models.py
from django.db import models

# Create your models here.

reactfilebrowser/views.py
from django.conf import settings
from django.http.response import JsonResponse
from django.shortcuts import render

from reactfilebrowser.helpers import path_to_dict


def get_root(request):
    path_dict = path_to_dict(settings.MEDIA_ROOT)
    resp = JsonResponse(path_dict)
    resp["Access-Control-Allow-Origin"] = "*"
    return resp


def get_browser(request, opener_id=None):
    response = render(request, "reactfilebrowser/index.html", {"opener_id": opener_id, "settings": settings})
    response["Access-Control-Allow-Origin"] = "*"
    return response


def test(request):
    return render(request, "reactfilebrowser/test.html")

reactfilebrowser/templates/reactfilebrowser/index.html
<!DOCTYPE html>
<html lang="en" style="height: 100%;">
<head>
    <meta charset="UTF-8">
    <title>File Chooser</title>
    <!-- CSS Global -->
    {% load staticfiles %}
    <link href="{% static "bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet"/>
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet"/>
</head>
<body style="height: 100%;">
<div id="chooser" class="container-fluid" style="height:100%;width:100%">
</div>
<script src="{% static "jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
<script src="{% static "reactfilebrowser/bundle.js" %}"></script>
<script>
    var input = window.opener.document.getElementById("{{ opener_id }}");
    console.log(
            input && input.hasOwnProperty("value") && input.value.length > 0,
            input.value.split(',')
    );
    chooser.open_file_browser({
        host: "{{ settings.REACT_FILE_BROWSER_HOST }}",
        host_file_url: "{{ settings.REACT_FILE_BROWSER_HOST }}{{ settings.MEDIA_URL }}",
        root_url: "{% url "reactfilebrowser:root" %}",
        selected: input && input.value.length > 0 ? input.value.split(',') : []
    })
</script>

</body>
</html>

reactfilebrowser/templates/reactfilebrowser/test.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>File Chooser</title>
    <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
</head>
<body>
<button data-rfb-target="#selected" data-rfn-root-api="{% url "reactfilebrowser:browser" %}"
        class="react-file-browser-field">open chooser
</button>
<input id="selected" type="text" readonly="true"/>
{% load staticfiles %}
<script>
    $(".react-file-browser-field").each(
            function () {
                var $self = $(this);
                $self.on("click", function () {
                    var params = [
                        'height=' + screen.height,
                        'width=' + screen.width,
                        'fullscreen=yes' // only works in IE, but here for completeness
                    ].join(',');
                    window.open($self.attr("data-rfn-root-api") + $self.attr("data-rfb-target"), "File Browser", params);
                    window.onmessage = function (e) {
                        document.getElementById("selected").value = JSON.parse(e.data).join(',');
                    }
                })
            }
    );
</script>
</body>
</html>